sudo: false
language: java
jdk:
    - openjdk8
cache:
    directories:
        - $HOME/.m2'
        - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "mkarpisek-github"
        
install: true
script: mvn clean verify sonar:sonar

after_success:
    - bash <(curl -s https://codecov.io/bash)